title: DeltaWerken
tagline: DeltaWerken delta 3D-printer
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://just-the-docs.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: DeltaWerken/deltawerken.github.io # for github-metadata
markdown: kramdown
permalink: pretty
remote_theme: pmarsceill/just-the-docs
color_scheme: "deltawerken"
search_enabled: true
timezone: Europe/Amsterdam
aux_links:
  "GitHub":
    - "//github.com/DeltaWerken/deltawerken.github.io"
  "Ko-Fi":
    - "https://ko-fi.com/maze"
aux_links_new_tab: true

#ga_tracking: G-6NEWMMGBTW
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

nav_external_links:
  - title: Join Our Discord
    url: https://discord.gg/jz2dTMYj5d
    hide_icon: false # set to true to hide the external link icon - defaults to false